name = "Batman"
print(len(name))
print(name.find("B"))
print(name.capitalize())
print((name.upper()))
print(name.lower())
print(name.isdigit())
print(name.isalpha())
print(name.count("a"))
print(name.replace("Batman","Obito "))
print(name * 3)